name: Build package

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build QuickJS package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: quickjs:ci

      - name: Create Docker container
        run: docker create --name quickjs quickjs:ci

      - name: Copy packages from container
        run: |
          mkdir -p ./bin
          docker cp quickjs:/builder/bin/packages/x86_64/lib/. ./bin/ || true
          docker cp quickjs:/builder/bin/packages/x86_64/packages/lib/. ./bin/ || true
          find ./bin -name "*.ipk" || echo "No IPK files found"

      - name: Remove Docker container
        run: docker rm quickjs

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/v') && steps.find.outputs.files != ''
        with:
          files: ./bin/*.ipk