name: CI/CD

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.2.1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: quickjs:ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Docker container
        run: docker create --name quickjs quickjs:ci

      - name: Copy packages from container
        run: |
          mkdir -p ./bin
          docker cp quickjs:/builder/bin/packages/aarch64_cortex-a53/utils/. ./bin/
          ls -la ./bin

      - name: Remove Docker container
        run: docker rm quickjs

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: ./bin/*.ipk
          if-no-files-found: error

  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: ./bin

      - name: Create release
        uses: softprops/action-gh-release@v2.0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./bin/*.ipk
          generate_release_notes: true